export const DASHBOARD_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Development Control Center</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#e8eef7;background:#09111f}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#09111f,#101d31);min-height:100vh}header{padding:22px 28px;border-bottom:1px solid #263956;display:flex;justify-content:space-between;align-items:center}h1{font-size:20px;letter-spacing:.08em;margin:0}nav button,.action{background:#172943;color:#dce9ff;border:1px solid #365278;border-radius:8px;padding:9px 13px;margin:4px;cursor:pointer}.action.primary{background:#2d6cdf}.action:disabled{opacity:.4;cursor:not-allowed}main{padding:24px;max-width:1400px;margin:auto}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}.card,.panel{background:#101d31cc;border:1px solid #263956;border-radius:12px;padding:16px}.card strong{display:block;font-size:28px;margin-top:8px}.panel{margin-top:16px}.task{display:grid;grid-template-columns:120px 1fr 160px 160px 100px;gap:12px;padding:12px;border-bottom:1px solid #263956;align-items:center}.pill{font-size:12px;border-radius:999px;padding:4px 9px;background:#243b5c;width:max-content}.pass{color:#6ee7a8}.fail{color:#ff7c89}.muted{color:#94a9c6}input,textarea{width:100%;background:#0a1526;color:#edf4ff;border:1px solid #365278;border-radius:8px;padding:10px}textarea{min-height:100px}pre{white-space:pre-wrap;overflow:auto;background:#08101d;padding:12px;border-radius:8px}.hidden{display:none}@media(max-width:760px){.task{grid-template-columns:1fr 1fr}.task span:nth-child(2){grid-column:1/-1}header{align-items:flex-start;gap:12px;flex-direction:column}}
</style></head><body><header><h1>AI DEVELOPMENT CONTROL CENTER</h1><nav><button data-page="overview">Overview</button><button data-page="tasks">Tasks</button><button data-page="agents">Agents</button><button data-page="cost">Cost</button><button data-page="settings">Settings</button></nav></header>
<main><section id="overview"><div id="cards" class="cards"></div><div class="panel"><h2>Run Task</h2><textarea id="taskInput" placeholder="Describe the development task"></textarea><button id="run" class="action primary">Run</button></div><div class="panel"><h2>Current Tasks</h2><div id="overviewTasks"></div></div></section>
<section id="tasks" class="hidden"><div class="panel"><h2>Tasks</h2><div id="taskList"></div></div><div id="detail" class="panel hidden"></div></section>
<section id="agents" class="hidden"><div class="panel"><h2>Agents</h2><div id="agentList"></div></div></section>
<section id="cost" class="hidden"><div class="panel"><h2>Usage</h2><pre id="usage"></pre></div></section>
<section id="settings" class="hidden"><div class="panel"><h2>Settings</h2><p class="muted">Configuration is loaded from harness.config.yaml. Secrets are never shown here.</p><pre id="config"></pre></div></section></main>
<script>
const request=window.fetch.bind(window);let state={tasks:[],overview:{},config:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));document.getElementById(b.dataset.page).classList.remove('hidden')});
document.getElementById('run').onclick=async()=>{const task=document.getElementById('taskInput').value.trim();if(!task)return;await request('/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task})});document.getElementById('taskInput').value='';await refresh()};
async function refresh(){state=await (await request('/api/overview')).json();render()}
function taskRow(t){return '<div class="task"><b>'+esc(t.id)+'</b><span>'+esc(t.title)+'</span><span class="pill">'+esc(t.phase)+'</span><span class="pill">'+esc(t.status)+'</span><button class="action" onclick="detail(&quot;'+esc(t.id)+'&quot;)">View</button></div>'}
function render(){const o=state.overview;document.getElementById('cards').innerHTML=['RUNNING','WAITING','BLOCKED','FAILED','COMPLETED'].map(k=>'<div class="card">'+k+'<strong>'+esc(o[k]||0)+'</strong></div>').join('')+'<div class="card">ACTIVE AGENTS<strong>'+esc(o.activeAgents||0)+'</strong></div>';const rows=state.tasks.map(taskRow).join('')||'<p class="muted">No tasks yet.</p>';document.getElementById('overviewTasks').innerHTML=rows;document.getElementById('taskList').innerHTML=rows;document.getElementById('agentList').innerHTML=(state.agents||[]).map(a=>'<div class="task"><b>'+esc(a.name)+'</b><span class="pill">'+esc(a.status)+'</span></div>').join('');document.getElementById('usage').textContent=JSON.stringify(state.usage,null,2);document.getElementById('config').textContent=JSON.stringify(state.config,null,2)}
window.detail=async id=>{const d=await (await request('/api/tasks/'+encodeURIComponent(id))).json();let ci={checks:[],readyToMerge:false};if(d.pullRequest){try{ci=await (await request('/api/tasks/'+encodeURIComponent(id)+'/ci')).json()}catch{}}const el=document.getElementById('detail');el.classList.remove('hidden');el.innerHTML='<h2>'+esc(d.task.id)+' Task Detail</h2><button class="action" onclick="retry(&quot;'+esc(id)+'&quot;)">Retry</button><button class="action" '+(ci.readyToMerge?'':'disabled')+' onclick="mergeTask(&quot;'+esc(id)+'&quot;)" title="Requires passing CI and explicit human approval">Merge</button><h3>CI</h3><pre>'+esc(JSON.stringify(ci,null,2))+'</pre><h3>Task</h3><pre>'+esc(JSON.stringify(d,null,2))+'</pre>'};
window.retry=async id=>{await request('/api/tasks/'+encodeURIComponent(id)+'/retry',{method:'POST'});await refresh();await detail(id)};
window.mergeTask=async id=>{if(!window.confirm('Merge this pull request after verified CI checks?'))return;const response=await request('/api/tasks/'+encodeURIComponent(id)+'/merge',{method:'POST'});if(!response.ok){window.alert((await response.json()).error||'Merge failed');return}await refresh();await detail(id)};
const events=new EventSource('/api/events');events.onmessage=e=>{try{state=JSON.parse(e.data);render()}catch{}};refresh();
</script></body></html>`;
